---
- name: Create systemd unit file from template
  ansible.builtin.template:
    src: container.service.j2
    dest: "{{ _edge_application_systemd_path }}/{{ _edge_application_systemd_unit_name }}"
    mode: "0644"
  notify:
    - Reload systemd daemon
    - Restart systemd unit

- name: Show where application is listening
  ansible.builtin.debug:
    msg: "Application listening on: {{ ansible_host }}:{{ edge_application_external_port }}"
